from src.ansible_matcher.commands.configs.apk import *
from src.ansible_matcher.commands.configs.apt import *
from src.ansible_matcher.commands.configs.cd import *
from src.ansible_matcher.commands.configs.chmod import *
from src.ansible_matcher.commands.configs.chown import *
from src.ansible_matcher.commands.configs.cp import *
from src.ansible_matcher.commands.configs.curl import *
from src.ansible_matcher.commands.configs.git import *
from src.ansible_matcher.commands.configs.ln import *
from src.ansible_matcher.commands.configs.make import *
from src.ansible_matcher.commands.configs.mkdir import *
from src.ansible_matcher.commands.configs.mv import *
from src.ansible_matcher.commands.configs.pip3 import *
from src.ansible_matcher.commands.configs.pip import *
from src.ansible_matcher.commands.configs.rm import *
from src.ansible_matcher.commands.configs.set import *
from src.ansible_matcher.commands.configs.sudo import *
from src.ansible_matcher.commands.configs.tar import *
from src.ansible_matcher.commands.configs.useradd import *
from src.ansible_matcher.commands.configs.wget import *

from src.ansible_matcher.commands.handlers.apk import *
from src.ansible_matcher.commands.handlers.apt import *
from src.ansible_matcher.commands.handlers.cd import *
from src.ansible_matcher.commands.handlers.chmod import *
from src.ansible_matcher.commands.handlers.chown import *
from src.ansible_matcher.commands.handlers.cp import *
from src.ansible_matcher.commands.handlers.curl import *
from src.ansible_matcher.commands.handlers.git import *
from src.ansible_matcher.commands.handlers.ln import *
from src.ansible_matcher.commands.handlers.make import *
from src.ansible_matcher.commands.handlers.mkdir import *
from src.ansible_matcher.commands.handlers.mv import *
from src.ansible_matcher.commands.handlers.pip3 import *
from src.ansible_matcher.commands.handlers.pip import *
from src.ansible_matcher.commands.handlers.rm import *
from src.ansible_matcher.commands.handlers.set import *
from src.ansible_matcher.commands.handlers.sudo import *
from src.ansible_matcher.commands.handlers.tar import *
from src.ansible_matcher.commands.handlers.useradd import *
from src.ansible_matcher.commands.handlers.wget import *
