commands_config = {
    "apt-get": {
        "command": {
            "name": "apt-get",
            "optionsAll": {
                "arrays": [
                    "-o",
                    "--option"
                ],
                "booleans": [
                    "--no-install-recommends",
                    "--install-suggests",
                    "-d",
                    "--download-only",
                    "-f",
                    "--fix-broken",
                    "-m",
                    "--ignore-missing",
                    "--fix-missing",
                    "--no-download",
                    "-s",
                    "--simulate",
                    "--just-print",
                    "--dry-run",
                    "--recon",
                    "--no-act",
                    "-y",
                    "--yes",
                    "--assume-yes",
                    "--assume-no",
                    "--no-show-upgraded",
                    "-V",
                    "--verbose-versions",
                    "-b",
                    "--compile",
                    "--build",
                    "--ignore-hold",
                    "--with-new-pkgs",
                    "--no-upgrade",
                    "--only-upgrade",
                    "--allow-downgrades",
                    "--allow-remove-essential",
                    "--allow-change-held-packages",
                    "--force-yes",
                    "--print-uris",
                    "--purge",
                    "--reinstall",
                    "--list-cleanup",
                    "--no-list-cleanup",
                    "--trivial-only",
                    "--no-remove",
                    "--auto-remove",
                    "--autoremove",
                    "--only-dockerfiles",
                    "--diff-only",
                    "--dsc-only",
                    "--tar-only",
                    "--arch-only",
                    "--indep-only",
                    "--allow-unauthenticated",
                    "--no-allow-insecure-repositories",
                    "--allow-releaseinfo-change",
                    "--show-progress",
                    "-h, --help",
                    "-v, --version"
                ],
                "counts": [
                    "-q",
                    "--quiet"
                ],
                "paths": [
                    "-c",
                    "--config-file",
                    "--with-dockerfiles",
                    "-a",
                    "--host-architecture",
                    "-P",
                    "--build-profiles",
                    "-t",
                    "--target-release",
                    "--default-release"
                ]
            },
            "scenarios": [
                {
                    "cmd": "$0 update",
                    "name": "apt-get update",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 upgrade",
                    "name": "apt-get upgrade",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 dist-upgrade",
                    "name": "apt-get dist-upgrade",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 dselect-upgrade",
                    "name": "apt-get dselect-upgrade",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 install [packages...]",
                    "name": "apt-get install",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 reinstall [packages...]",
                    "name": "apt-get reinstall",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 remove [packages...]",
                    "name": "apt-get remove",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 purge [packages...]",
                    "name": "apt-get purge",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 dockerfiles [packages...]",
                    "name": "apt-get dockerfiles",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 build-dep [packages...]",
                    "name": "apt-get build-dep",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 satisfy [dependencies...]",
                    "name": "apt-get satisfy",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 check",
                    "name": "apt-get check",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 download [packages...]",
                    "name": "apt-get download",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 clean",
                    "name": "apt-get clean",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 autoclean",
                    "name": "apt-get autoclean",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 auto-clean",
                    "name": "apt-get autoclean",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 autoremove",
                    "name": "apt-get autoremove",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 auto-remove",
                    "name": "apt-get autoremove",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 changelog [packages...]",
                    "name": "apt-get changelog",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                },
                {
                    "cmd": "$0 indextargets",
                    "name": "apt-get indextargets",
                    "options": {
                        "arrays": [
                            "-o",
                            "--option"
                        ],
                        "booleans": [
                            "--no-install-recommends",
                            "--install-suggests",
                            "-d",
                            "--download-only",
                            "-f",
                            "--fix-broken",
                            "-m",
                            "--ignore-missing",
                            "--fix-missing",
                            "--no-download",
                            "-s",
                            "--simulate",
                            "--just-print",
                            "--dry-run",
                            "--recon",
                            "--no-act",
                            "-y",
                            "--yes",
                            "--assume-yes",
                            "--assume-no",
                            "--no-show-upgraded",
                            "-V",
                            "--verbose-versions",
                            "-b",
                            "--compile",
                            "--build",
                            "--ignore-hold",
                            "--with-new-pkgs",
                            "--no-upgrade",
                            "--only-upgrade",
                            "--allow-downgrades",
                            "--allow-remove-essential",
                            "--allow-change-held-packages",
                            "--force-yes",
                            "--print-uris",
                            "--purge",
                            "--reinstall",
                            "--list-cleanup",
                            "--no-list-cleanup",
                            "--trivial-only",
                            "--no-remove",
                            "--auto-remove",
                            "--autoremove",
                            "--only-dockerfiles",
                            "--diff-only",
                            "--dsc-only",
                            "--tar-only",
                            "--arch-only",
                            "--indep-only",
                            "--allow-unauthenticated",
                            "--no-allow-insecure-repositories",
                            "--allow-releaseinfo-change",
                            "--show-progress",
                            "-h, --help",
                            "-v, --version"
                        ],
                        "counts": [
                            "-q",
                            "--quiet"
                        ],
                        "paths": [
                            "-c",
                            "--config-file",
                            "--with-dockerfiles",
                            "-a",
                            "--host-architecture",
                            "-P",
                            "--build-profiles",
                            "-t",
                            "--target-release",
                            "--default-release"
                        ]
                    }
                }
            ]
        }
    },
    "echo": {
        "command": {
            "name": "echo",
            "scenarios": [
                {
                    "cmd": "$0 [items...]",
                    "name": "echo",
                    "options": {
                        "booleans": [
                            "-n",
                            "-e",
                            "-E",
                            "--version",
                            "--help"
                        ]
                    }
                }
            ]
        }
    },
    "rm": {
        "command": {
            "name": "rm",
            "scenarios": [
                {
                    "cmd": "$0 [paths...]",
                    "name": "rm",
                    "options": {
                        "booleans": [
                            "-r",
                            "--recursive",
                            "-R",
                            "--recursive",
                            "-f",
                            "--force",
                            "-i",
                            "-I",
                            "--one-file-system",
                            "-v",
                            "--verbose",
                            "--version",
                            "--help",
                            "--preserve-root",
                            "--no-preserve-root"
                        ],
                        "strings": [
                            "--interactive"
                        ]
                    }
                }
            ]
        }
    }
}
