# Generated by ANTLR 4.10.1
# encoding: utf-8
from antlr4 import *
from io import StringIO
import sys
if sys.version_info[1] > 5:
	from typing import TextIO
else:
	from typing.io import TextIO

def serializedATN():
    return [
        4,1,11,41,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,1,0,1,0,1,0,5,0,12,8,0,
        10,0,12,0,15,9,0,1,1,1,1,4,1,19,8,1,11,1,12,1,20,1,2,1,2,1,3,1,3,
        1,3,1,3,3,3,29,8,3,1,3,3,3,32,8,3,1,3,3,3,35,8,3,3,3,37,8,3,1,3,
        1,3,1,3,0,0,4,0,2,4,6,0,0,43,0,8,1,0,0,0,2,18,1,0,0,0,4,22,1,0,0,
        0,6,24,1,0,0,0,8,13,3,2,1,0,9,10,5,3,0,0,10,12,3,2,1,0,11,9,1,0,
        0,0,12,15,1,0,0,0,13,11,1,0,0,0,13,14,1,0,0,0,14,1,1,0,0,0,15,13,
        1,0,0,0,16,19,3,4,2,0,17,19,3,6,3,0,18,16,1,0,0,0,18,17,1,0,0,0,
        19,20,1,0,0,0,20,18,1,0,0,0,20,21,1,0,0,0,21,3,1,0,0,0,22,23,5,2,
        0,0,23,5,1,0,0,0,24,25,5,1,0,0,25,36,5,4,0,0,26,28,5,5,0,0,27,29,
        5,8,0,0,28,27,1,0,0,0,28,29,1,0,0,0,29,31,1,0,0,0,30,32,5,9,0,0,
        31,30,1,0,0,0,31,32,1,0,0,0,32,34,1,0,0,0,33,35,5,10,0,0,34,33,1,
        0,0,0,34,35,1,0,0,0,35,37,1,0,0,0,36,26,1,0,0,0,36,37,1,0,0,0,37,
        38,1,0,0,0,38,39,5,6,0,0,39,7,1,0,0,0,7,13,18,20,28,31,34,36
    ]

class CommandTemplateParser ( Parser ):

    grammarFileName = "CommandTemplateParser.g4"

    atn = ATNDeserializer().deserialize(serializedATN())

    decisionsToDFA = [ DFA(ds, i) for i, ds in enumerate(atn.decisionToState) ]

    sharedContextCache = PredictionContextCache()

    literalNames = [ "<INVALID>", "'{{'", "<INVALID>", "<INVALID>", "<INVALID>", 
                     "':'", "'}}'", "<INVALID>", "'m'", "'o'", "'p'" ]

    symbolicNames = [ "<INVALID>", "OPEN", "WORD", "SPACE", "FIELD_NAME", 
                      "SPEC_OPEN", "CLOSE", "INSIDE_S", "SPEC_MANY", "SPEC_OPTIONAL", 
                      "SPEC_PATH", "SPECS_S" ]

    RULE_command_template = 0
    RULE_template_object = 1
    RULE_template_word = 2
    RULE_template_field = 3

    ruleNames =  [ "command_template", "template_object", "template_word", 
                   "template_field" ]

    EOF = Token.EOF
    OPEN=1
    WORD=2
    SPACE=3
    FIELD_NAME=4
    SPEC_OPEN=5
    CLOSE=6
    INSIDE_S=7
    SPEC_MANY=8
    SPEC_OPTIONAL=9
    SPEC_PATH=10
    SPECS_S=11

    def __init__(self, input:TokenStream, output:TextIO = sys.stdout):
        super().__init__(input, output)
        self.checkVersion("4.10.1")
        self._interp = ParserATNSimulator(self, self.atn, self.decisionsToDFA, self.sharedContextCache)
        self._predicates = None




    class Command_templateContext(ParserRuleContext):
        __slots__ = 'parser'

        def __init__(self, parser, parent:ParserRuleContext=None, invokingState:int=-1):
            super().__init__(parent, invokingState)
            self.parser = parser

        def template_object(self, i:int=None):
            if i is None:
                return self.getTypedRuleContexts(CommandTemplateParser.Template_objectContext)
            else:
                return self.getTypedRuleContext(CommandTemplateParser.Template_objectContext,i)


        def SPACE(self, i:int=None):
            if i is None:
                return self.getTokens(CommandTemplateParser.SPACE)
            else:
                return self.getToken(CommandTemplateParser.SPACE, i)

        def getRuleIndex(self):
            return CommandTemplateParser.RULE_command_template

        def enterRule(self, listener:ParseTreeListener):
            if hasattr( listener, "enterCommand_template" ):
                listener.enterCommand_template(self)

        def exitRule(self, listener:ParseTreeListener):
            if hasattr( listener, "exitCommand_template" ):
                listener.exitCommand_template(self)

        def accept(self, visitor:ParseTreeVisitor):
            if hasattr( visitor, "visitCommand_template" ):
                return visitor.visitCommand_template(self)
            else:
                return visitor.visitChildren(self)




    def command_template(self):

        localctx = CommandTemplateParser.Command_templateContext(self, self._ctx, self.state)
        self.enterRule(localctx, 0, self.RULE_command_template)
        self._la = 0 # Token type
        try:
            self.enterOuterAlt(localctx, 1)
            self.state = 8
            self.template_object()
            self.state = 13
            self._errHandler.sync(self)
            _la = self._input.LA(1)
            while _la==CommandTemplateParser.SPACE:
                self.state = 9
                self.match(CommandTemplateParser.SPACE)
                self.state = 10
                self.template_object()
                self.state = 15
                self._errHandler.sync(self)
                _la = self._input.LA(1)

        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.exitRule()
        return localctx


    class Template_objectContext(ParserRuleContext):
        __slots__ = 'parser'

        def __init__(self, parser, parent:ParserRuleContext=None, invokingState:int=-1):
            super().__init__(parent, invokingState)
            self.parser = parser

        def template_word(self, i:int=None):
            if i is None:
                return self.getTypedRuleContexts(CommandTemplateParser.Template_wordContext)
            else:
                return self.getTypedRuleContext(CommandTemplateParser.Template_wordContext,i)


        def template_field(self, i:int=None):
            if i is None:
                return self.getTypedRuleContexts(CommandTemplateParser.Template_fieldContext)
            else:
                return self.getTypedRuleContext(CommandTemplateParser.Template_fieldContext,i)


        def getRuleIndex(self):
            return CommandTemplateParser.RULE_template_object

        def enterRule(self, listener:ParseTreeListener):
            if hasattr( listener, "enterTemplate_object" ):
                listener.enterTemplate_object(self)

        def exitRule(self, listener:ParseTreeListener):
            if hasattr( listener, "exitTemplate_object" ):
                listener.exitTemplate_object(self)

        def accept(self, visitor:ParseTreeVisitor):
            if hasattr( visitor, "visitTemplate_object" ):
                return visitor.visitTemplate_object(self)
            else:
                return visitor.visitChildren(self)




    def template_object(self):

        localctx = CommandTemplateParser.Template_objectContext(self, self._ctx, self.state)
        self.enterRule(localctx, 2, self.RULE_template_object)
        self._la = 0 # Token type
        try:
            self.enterOuterAlt(localctx, 1)
            self.state = 18 
            self._errHandler.sync(self)
            _la = self._input.LA(1)
            while True:
                self.state = 18
                self._errHandler.sync(self)
                token = self._input.LA(1)
                if token in [CommandTemplateParser.WORD]:
                    self.state = 16
                    self.template_word()
                    pass
                elif token in [CommandTemplateParser.OPEN]:
                    self.state = 17
                    self.template_field()
                    pass
                else:
                    raise NoViableAltException(self)

                self.state = 20 
                self._errHandler.sync(self)
                _la = self._input.LA(1)
                if not (_la==CommandTemplateParser.OPEN or _la==CommandTemplateParser.WORD):
                    break

        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.exitRule()
        return localctx


    class Template_wordContext(ParserRuleContext):
        __slots__ = 'parser'

        def __init__(self, parser, parent:ParserRuleContext=None, invokingState:int=-1):
            super().__init__(parent, invokingState)
            self.parser = parser

        def WORD(self):
            return self.getToken(CommandTemplateParser.WORD, 0)

        def getRuleIndex(self):
            return CommandTemplateParser.RULE_template_word

        def enterRule(self, listener:ParseTreeListener):
            if hasattr( listener, "enterTemplate_word" ):
                listener.enterTemplate_word(self)

        def exitRule(self, listener:ParseTreeListener):
            if hasattr( listener, "exitTemplate_word" ):
                listener.exitTemplate_word(self)

        def accept(self, visitor:ParseTreeVisitor):
            if hasattr( visitor, "visitTemplate_word" ):
                return visitor.visitTemplate_word(self)
            else:
                return visitor.visitChildren(self)




    def template_word(self):

        localctx = CommandTemplateParser.Template_wordContext(self, self._ctx, self.state)
        self.enterRule(localctx, 4, self.RULE_template_word)
        try:
            self.enterOuterAlt(localctx, 1)
            self.state = 22
            self.match(CommandTemplateParser.WORD)
        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.exitRule()
        return localctx


    class Template_fieldContext(ParserRuleContext):
        __slots__ = 'parser'

        def __init__(self, parser, parent:ParserRuleContext=None, invokingState:int=-1):
            super().__init__(parent, invokingState)
            self.parser = parser

        def OPEN(self):
            return self.getToken(CommandTemplateParser.OPEN, 0)

        def FIELD_NAME(self):
            return self.getToken(CommandTemplateParser.FIELD_NAME, 0)

        def CLOSE(self):
            return self.getToken(CommandTemplateParser.CLOSE, 0)

        def SPEC_OPEN(self):
            return self.getToken(CommandTemplateParser.SPEC_OPEN, 0)

        def SPEC_MANY(self):
            return self.getToken(CommandTemplateParser.SPEC_MANY, 0)

        def SPEC_OPTIONAL(self):
            return self.getToken(CommandTemplateParser.SPEC_OPTIONAL, 0)

        def SPEC_PATH(self):
            return self.getToken(CommandTemplateParser.SPEC_PATH, 0)

        def getRuleIndex(self):
            return CommandTemplateParser.RULE_template_field

        def enterRule(self, listener:ParseTreeListener):
            if hasattr( listener, "enterTemplate_field" ):
                listener.enterTemplate_field(self)

        def exitRule(self, listener:ParseTreeListener):
            if hasattr( listener, "exitTemplate_field" ):
                listener.exitTemplate_field(self)

        def accept(self, visitor:ParseTreeVisitor):
            if hasattr( visitor, "visitTemplate_field" ):
                return visitor.visitTemplate_field(self)
            else:
                return visitor.visitChildren(self)




    def template_field(self):

        localctx = CommandTemplateParser.Template_fieldContext(self, self._ctx, self.state)
        self.enterRule(localctx, 6, self.RULE_template_field)
        self._la = 0 # Token type
        try:
            self.enterOuterAlt(localctx, 1)
            self.state = 24
            self.match(CommandTemplateParser.OPEN)
            self.state = 25
            self.match(CommandTemplateParser.FIELD_NAME)
            self.state = 36
            self._errHandler.sync(self)
            _la = self._input.LA(1)
            if _la==CommandTemplateParser.SPEC_OPEN:
                self.state = 26
                self.match(CommandTemplateParser.SPEC_OPEN)
                self.state = 28
                self._errHandler.sync(self)
                _la = self._input.LA(1)
                if _la==CommandTemplateParser.SPEC_MANY:
                    self.state = 27
                    self.match(CommandTemplateParser.SPEC_MANY)


                self.state = 31
                self._errHandler.sync(self)
                _la = self._input.LA(1)
                if _la==CommandTemplateParser.SPEC_OPTIONAL:
                    self.state = 30
                    self.match(CommandTemplateParser.SPEC_OPTIONAL)


                self.state = 34
                self._errHandler.sync(self)
                _la = self._input.LA(1)
                if _la==CommandTemplateParser.SPEC_PATH:
                    self.state = 33
                    self.match(CommandTemplateParser.SPEC_PATH)




            self.state = 38
            self.match(CommandTemplateParser.CLOSE)
        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.exitRule()
        return localctx





